# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2441eb2c705c7ba5c94a79c914284097726c315f834db7a33759e1bac3e26c2167c744996d097627004a6363ffdc64b52dea23a03c7d1c2c1960a39ace1141d2

test:
  secret_key_base: 5b34ec6e245ead7228565ad7401cde240414911b44bad8d8a574a5ed53fc9b236e1dd1aeeeada9b190a5e3324576faaa7eba8c93e11ff2cad994a424afbc55ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
